# If you come from bash you might have to change your $PATH.
export PATH=/usr/local/bin:$HOME/bin:$PATH

# term colors
export TERM=xterm-256color

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Theme inside emacs and otherwise
if [ -n "$INSIDE_EMACS" ]; then
  export ZSH_THEME="candy"
else
  export ZSH_THEME="robbyrussell"
fi

# Vi-mode for zsh
bindkey jk vi-cmd-mode

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# SSH
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Aliases
alias gs='git status'

# Homebrew at front of the path
#export PATH=/usr/local/bin:$PATH

# Added by Miniconda3 4.3.21 installer
#export PATH="$HOME/miniconda3/bin:$PATH"

# ROS
#source /opt/ros/indigo/setup.zsh

# Add path for ~/bin dir
#export PATH="$HOME/bin:$PATH"

# virtualenv
export WORKON_HOME=~/Virtualenvs
source /usr/local/bin/virtualenvwrapper.sh

# Google Cloud API keys
export GOOGLE_APPLICATION_CREDENTIALS=$HOME/Documents/My\ First\ Project-437de8f4dd3e.json

alias py="python3 trainer.py \
--ps_hosts=10.174.108.121:2222 \
--worker_hosts=10.174.6.143:2222 \
--job_name=ps --task_index=0"