# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Theme inside emacs and otherwise
if [ -n "$INSIDE_EMACS" ]; then
  export ZSH_THEME="candy"
else
  export ZSH_THEME="robbyrussell"
fi

# Vi-mode for zsh
bindkey jk vi-cmd-mode

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# SSH
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Aliases
alias gs='git status'

# Added by Miniconda3 4.3.21 installer
export PATH="$HOME/miniconda3/bin:$PATH"

# ROS
source /opt/ros/indigo/setup.zsh

# Add path for ~/bin dir
export PATH="$HOME/bin:$PATH"
